set(_CATKIN_CURRENT_PACKAGE "ambercortex_ros")
set(ambercortex_ros_VERSION "0.0.0")
set(ambercortex_ros_MAINTAINER "petter <pettni@caltech.edu>")
set(ambercortex_ros_PACKAGE_FORMAT "2")
set(ambercortex_ros_BUILD_DEPENDS "roscpp" "message_generation")
set(ambercortex_ros_BUILD_EXPORT_DEPENDS "roscpp" "message_generation")
set(ambercortex_ros_BUILDTOOL_DEPENDS "catkin")
set(ambercortex_ros_BUILDTOOL_EXPORT_DEPENDS )
set(ambercortex_ros_EXEC_DEPENDS "message_runtime" "roscpp" "message_generation")
set(ambercortex_ros_RUN_DEPENDS "message_runtime" "roscpp" "message_generation")
set(ambercortex_ros_TEST_DEPENDS )
set(ambercortex_ros_DOC_DEPENDS )
set(ambercortex_ros_URL_WEBSITE "")
set(ambercortex_ros_URL_BUGTRACKER "")
set(ambercortex_ros_URL_REPOSITORY "")
set(ambercortex_ros_DEPRECATED "")